name: Update README.md Recent Activity section
run-name: Automated update
on:
  schedule:
    - cron: '*/30 * * * *' # Update every 30 minutes
  workflow_dispatch: # allows you to manually trigger workflow from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
